package co.libly.hydride;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class hydro_kx_keypair extends Structure {
	public byte[] pk = new byte[32];
	public byte[] sk = new byte[32];
	public hydro_kx_keypair() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("pk", "sk");
	}
	public hydro_kx_keypair(byte pk[], byte sk[]) {
		super();
		if ((pk.length != this.pk.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pk = pk;
		if ((sk.length != this.sk.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.sk = sk;
	}
	public hydro_kx_keypair(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends hydro_kx_keypair implements Structure.ByReference {
		
	};
	public static class ByValue extends hydro_kx_keypair implements Structure.ByValue {
		
	};
}
