package co.libly.hydride;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class hydro_kx_state extends Structure {
	public hydro_kx_keypair eph_kp;
	public hydro_hash_state h_st;
	public hydro_kx_state() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("eph_kp", "h_st");
	}
	public hydro_kx_state(hydro_kx_keypair eph_kp, hydro_hash_state h_st) {
		super();
		this.eph_kp = eph_kp;
		this.h_st = h_st;
	}
	public hydro_kx_state(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends hydro_kx_state implements Structure.ByReference {
		
	};
	public static class ByValue extends hydro_kx_state implements Structure.ByValue {
		
	};
}
