package co.libly.hydride;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class hydro_sign_state extends Structure {
	public hydro_hash_state hash_st;
	public hydro_sign_state() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("hash_st");
	}
	public hydro_sign_state(hydro_hash_state hash_st) {
		super();
		this.hash_st = hash_st;
	}
	public hydro_sign_state(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends hydro_sign_state implements Structure.ByReference {
		
	};
	public static class ByValue extends hydro_sign_state implements Structure.ByValue {
		
	};
}
