package co.libly.hydride;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class hydro_hash_state extends Structure {
	public int[] state = new int[12];
	public byte buf_off;
	public byte[] align = new byte[3];
	public hydro_hash_state() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("state", "buf_off", "align");
	}
	public hydro_hash_state(int state[], byte buf_off, byte align[]) {
		super();
		if ((state.length != this.state.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.state = state;
		this.buf_off = buf_off;
		if ((align.length != this.align.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.align = align;
	}
	public hydro_hash_state(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends hydro_hash_state implements Structure.ByReference {
		
	};
	public static class ByValue extends hydro_hash_state implements Structure.ByValue {
		
	};
}
